import fs from "node:fs";
import { config } from "./config";
import type { WordTiming } from "./captions";

// Local, open-source, free transcription fallback for reels whose voiceover
// predates the ElevenLabs alignment capture (or wasn't generated by this
// app at all). Runs Whisper fully in-process via ONNX (no Python, no API
// call, no per-use cost) — only used when a reel has no stored alignment.

// Lazy singleton: the model (tens of MB) is downloaded once on first use and
// cached in-process; repeated calls in the same server process reuse it.
let transcriberPromise: Promise<
  (
    input: Float32Array,
    options: Record<string, unknown>
  ) => Promise<{ chunks?: { text: string; timestamp: [number, number | null] }[] }>
> | null = null;

async function getTranscriber() {
  if (!transcriberPromise) {
    transcriberPromise = (async () => {
      const { pipeline } = await import("@huggingface/transformers");
      return (await pipeline(
        "automatic-speech-recognition",
        config.whisperModel
      )) as unknown as (
        input: Float32Array,
        options: Record<string, unknown>
      ) => Promise<{
        chunks?: { text: string; timestamp: [number, number | null] }[];
      }>;
    })();
  }
  return transcriberPromise;
}

// Minimal RIFF/WAVE PCM parser for the 16kHz mono WAV ffmpeg produces
// (see extractAudioForTranscription in ffmpeg.ts). Avoids depending on
// transformers.js's own local-file audio loading, which varies by version.
function readWavAsFloat32(wavPath: string): Float32Array {
  const buf = fs.readFileSync(wavPath);
  if (buf.toString("ascii", 0, 4) !== "RIFF" || buf.toString("ascii", 8, 12) !== "WAVE") {
    throw new Error(`${wavPath} is not a RIFF/WAVE file`);
  }
  let offset = 12;
  let dataStart = -1;
  let dataLength = 0;
  let bitsPerSample = 16;
  let numChannels = 1;
  while (offset + 8 <= buf.length) {
    const chunkId = buf.toString("ascii", offset, offset + 4);
    const chunkSize = buf.readUInt32LE(offset + 4);
    const chunkBody = offset + 8;
    if (chunkId === "fmt ") {
      numChannels = buf.readUInt16LE(chunkBody + 2);
      bitsPerSample = buf.readUInt16LE(chunkBody + 14);
    } else if (chunkId === "data") {
      dataStart = chunkBody;
      dataLength = chunkSize;
    }
    offset = chunkBody + chunkSize + (chunkSize % 2);
  }
  if (dataStart === -1) throw new Error(`${wavPath}: no data chunk found`);
  if (bitsPerSample !== 16 || numChannels !== 1) {
    throw new Error(
      `${wavPath}: expected 16-bit mono PCM, got ${bitsPerSample}-bit/${numChannels}ch`
    );
  }
  const sampleCount = dataLength / 2;
  const out = new Float32Array(sampleCount);
  for (let i = 0; i < sampleCount; i++) {
    out[i] = buf.readInt16LE(dataStart + i * 2) / 32768;
  }
  return out;
}

export async function transcribeWavForWordTimings(
  wavPath: string
): Promise<WordTiming[]> {
  const audio = readWavAsFloat32(wavPath);
  const transcriber = await getTranscriber();

  const timeoutMs = config.captionsTranscribeTimeoutMs;
  const result = await Promise.race([
    transcriber(audio, {
      return_timestamps: "word",
      chunk_length_s: 30,
      stride_length_s: 5,
    }),
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("Local transcription timed out")), timeoutMs)
    ),
  ]);

  const chunks = result.chunks ?? [];
  if (chunks.length === 0) {
    throw new Error("Transcription produced no word-level timestamps.");
  }

  const audioDurationSeconds = audio.length / 16000;
  return chunks
    .map((c) => ({
      word: c.text.trim(),
      // The final word's end timestamp can come back null when Whisper
      // doesn't detect silence before the clip ends — clamp to the audio's
      // actual duration rather than dropping the word.
      start: c.timestamp[0],
      end: c.timestamp[1] ?? audioDurationSeconds,
    }))
    .filter((w) => w.word.length > 0);
}
